name: Build and Save Dekart Docker Image

on:
  workflow_dispatch: # Allows you to run the workflow manually from GitHub
  # schedule:
  #   - cron: '0 0 * * 0' # Optional: Runs automatically every week

jobs:
  build-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file for Docker Compose
        run: |
          cat > .env << EOF
          DOCKER_COMPOSE_IMAGE=dekart-custom:latest
          DEKART_POSTGRES_PASSWORD=dekart
          DEKART_POSTGRES_USER=dekart
          DEKART_POSTGRES_DB=dekart
          DEKART_MAPBOX_TOKEN=
          DEKART_ALLOW_FILE_UPLOAD=1
          DEKART_STORAGE=GCS
          DEKART_DATASOURCE=BQ
          EOF

      - name: Build Docker image
        run: |
          docker build -t dekart-custom:latest .

      - name: Save Docker image as tar.gz
        run: |
          docker save dekart-custom:latest | gzip > dekart-custom.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dekart-image
          path: dekart-custom.tar.gz
          retention-days: 7
